"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { useSearchParams } from "next/navigation";
import { useChatNotifications } from "@/components/hooks/useChatNotifications";
import { ProtectedRoute } from "@/components/auth/protected-route";
import { DashboardLayout } from "@/components/layout/dashboard-layout";
import ChatRealtime from "@/components/chat/ChatRealtime";
import { dataService, type StudentItem } from "@/lib/data-service";
import { Avatar, AvatarFallback } from "@/components/ui/avatar";
import { Search, CheckCircle } from "lucide-react";
import {
  Dialog,
  DialogContent,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { toast } from "@/components/ui/use-toast";
import {
  createTicket,
  getOpciones,
  updateTicket,
  getStudentTickets,
  type OpcionItem,
} from "../admin/alumnos/api";

function normalize(s: string) {
  return s
    .toLowerCase()
    .normalize("NFD")
    .replace(/\p{Diacritic}/gu, "")
    .trim();
}

function getInitials(name: string): string {
  return name
    .split(" ")
    .map((n) => n[0])
    .join("")
    .toUpperCase()
    .slice(0, 2);
}

function getAvatarColor(name: string): string {
  const colors = [
    "bg-gray-400",
    "bg-gray-500",
    "bg-slate-400",
    "bg-slate-500",
    "bg-zinc-400",
    "bg-zinc-500",
  ];
  const index = name.charCodeAt(0) % colors.length;
  return colors[index];
}

export default function ChatHubPage() {
  const search = useSearchParams();
  const { unreadByRoom } = useChatNotifications({
    role: "admin",
    enableToast: false,
  });

  // Helper para leer estado de lectura local
  function getLastRead(room: string): number {
    if (typeof window === "undefined") return 0;
    try {
      const key = `chatLastRead:${room}:admin`;
      const raw = localStorage.getItem(key);
      return raw ? parseInt(raw, 10) : 0;
    } catch {
      return 0;
    }
  }

  const transport = (search?.get("transport") === "local" ? "local" : "ws") as
    | "local"
    | "ws";
  const debug = search?.get("debug") === "1";
  const [q, setQ] = useState("");
  // filtros por estado y fase para la lista de chats (alumnos)
  const [statusFilter, setStatusFilter] = useState<string | null>(null);
  const [phaseFilter, setPhaseFilter] = useState<string | null>(null);
  const statusOptions = ["EN_CURSO", "COMPLETADO", "ABANDONO", "PAUSA"];
  const phaseOptions = ["ONBOARDING", "F1", "F2", "F3", "F4", "F5"];
  const [all, setAll] = useState<StudentItem[]>([]);
  const [loading, setLoading] = useState(false);
  const [selected, setSelected] = useState<StudentItem | null>(null);
  // Modal creación de ticket desde selección del chat
  const [showTicket, setShowTicket] = useState(false);
  const [ticketNombre, setTicketNombre] = useState("");
  const [ticketTipo, setTicketTipo] = useState<string>("");
  const [ticketTipos, setTicketTipos] = useState<OpcionItem[]>([]);
  const [ticketArea, setTicketArea] = useState<string>("");
  const [ticketAreas, setTicketAreas] = useState<OpcionItem[]>([]);
  const [ticketArchivos, setTicketArchivos] = useState<File[]>([]);
  const [ticketPreviewMessages, setTicketPreviewMessages] = useState<any[]>([]);
  const [ticketAutoGenerated, setTicketAutoGenerated] = useState(false);
  const [ticketDescripcion, setTicketDescripcion] = useState("");
  const alumnoCodeForTicketRef = useRef<string | null>(null);
  const filePickerRef = useRef<HTMLInputElement | null>(null);
  // Estado para mostrar payload del ticket creado
  const [createdTicketPayload, setCreatedTicketPayload] = useState<any>(null);
  const [showCreatedModal, setShowCreatedModal] = useState(false);

  // Resumen derivado para mostrar en el modal de confirmación (tipo, usuario, fecha)
  const createdSummary = useMemo(() => {
    if (!createdTicketPayload) return null;
    // intentar obtener área/tipo
    let tipoLabel: string | null = null;
    // payload puede incluir 'tipo' (key) o 'tipo_key' o 'tipo_nombre'
    const tipoKey =
      createdTicketPayload.tipo ?? createdTicketPayload.tipo_key ?? null;
    if (tipoKey) {
      const opt = ticketTipos.find((t) => t.key === tipoKey);
      tipoLabel = opt?.value ?? String(tipoKey);
    }
    if (!tipoLabel && ticketTipo)
      tipoLabel =
        ticketTipos.find((t) => t.key === ticketTipo)?.value ?? ticketTipo;

    // usuario: buscar en la lista `all` por el código guardado en alumnoCodeForTicketRef
    const alumnoCode = alumnoCodeForTicketRef.current;
    const alumnoName = alumnoCode
      ? all.find(
          (s) =>
            (s.code || "").toLowerCase() === (alumnoCode || "").toLowerCase()
        )?.name ?? alumnoCode
      : "—";

    // fecha: usar campo del payload si existe, sino ahora
    const dateRaw =
      createdTicketPayload.creacion ??
      createdTicketPayload.created_at ??
      createdTicketPayload.createdAt ??
      new Date().toISOString();
    let dateFormatted = "";
    try {
      dateFormatted = new Date(dateRaw).toLocaleString("es-ES", {
        dateStyle: "medium",
        timeStyle: "short",
      });
    } catch {
      dateFormatted = String(dateRaw);
    }

    return {
      tipo: tipoLabel ?? "General",
      alumno: alumnoName,
      fecha: dateFormatted,
    };
  }, [createdTicketPayload, ticketTipos, ticketTipo, all]);

  useEffect(() => {
    let alive = true;
    (async () => {
      setLoading(true);
      try {
        const res = await dataService.getStudents({ pageSize: 500 });
        if (!alive) return;
        setAll(res.items ?? []);
      } catch {
        if (!alive) return;
        setAll([]);
      } finally {
        if (alive) setLoading(false);
      }
    })();
    return () => {
      alive = false;
    };
  }, []);

  const filtered = useMemo(() => {
    const k = normalize(q);
    let list = all;
    if (k) {
      list = list.filter((s) =>
        [s.name, s.code, s.stage, s.state]
          .filter(Boolean)
          .join(" ")
          .toLowerCase()
          .includes(k)
      );
    }
    // aplicar filtros por estado/fase (si seleccionados)
    if (statusFilter) {
      list = list.filter(
        (s) =>
          (
            ((s as any).state || (s as any).status || "") as string
          ).toUpperCase() === statusFilter
      );
    }
    if (phaseFilter) {
      list = list.filter(
        (s) =>
          (
            ((s as any).stage || (s as any).phase || "") as string
          ).toUpperCase() === phaseFilter
      );
    }
    return list;
  }, [all, q, statusFilter, phaseFilter]);

  // Detectar móvil para cambiar layout a maestro-detalle
  const [isMobile, setIsMobile] = useState(false);
  useEffect(() => {
    if (typeof window === "undefined") return;
    const mq = window.matchMedia("(max-width: 1024px)");
    const on = () => setIsMobile(mq.matches);
    on();
    mq.addEventListener?.("change", on);
    return () => mq.removeEventListener?.("change", on);
  }, []);

  // Escuchar evento del chat para crear ticket con selección
  useEffect(() => {
    const base64ToFile = (base64: string, name: string, mime: string): File => {
      try {
        const binary = atob(base64);
        const len = binary.length;
        const bytes = new Uint8Array(len);
        for (let i = 0; i < len; i++) bytes[i] = binary.charCodeAt(i);
        const blob = new Blob([bytes], {
          type: mime || "application/octet-stream",
        });
        return new File([blob], name || "archivo", {
          type: mime || "application/octet-stream",
        });
      } catch {
        // fallback vacío
        return new File([new Blob([])], name || "archivo", {
          type: mime || "application/octet-stream",
        });
      }
    };

    const handler = async (ev: Event) => {
      const detail = (ev as CustomEvent).detail as
        | { room: string; selected: any[] }
        | undefined;
      if (!detail) return;
      const room = (detail.room || "").toLowerCase();
      const alumno = all.find((s) => (s.code || "").toLowerCase() === room);
      const alumnoCode = alumno?.code || room;
      alumnoCodeForTicketRef.current = alumnoCode || null;

      // Recopilar adjuntos de los mensajes seleccionados (máx 10)
      const files: File[] = [];
      for (const m of detail.selected || []) {
        const atts = Array.isArray(m.attachments) ? m.attachments : [];
        for (const a of atts) {
          if (files.length >= 10) break;
          if (!a?.data_base64) continue;
          const f = base64ToFile(
            String(a.data_base64),
            String(a.name || "archivo"),
            String(a.mime || "application/octet-stream")
          );
          files.push(f);
        }
        if (files.length >= 10) break;
      }

      // Nombre por defecto desde primer mensaje con texto
      const firstWithText = (detail.selected || []).find((m) =>
        (m?.text || "").trim()
      );
      const nombre = (firstWithText?.text || "Ticket desde chat").slice(0, 80);

      // Si el detalle no es final, solo prellenar el modal para revisión
      if (!((detail as any).final === true)) {
        try {
          const [opTipos, opAreas] = await Promise.all([
            getOpciones("tipo_ticket"),
            getOpciones("area"),
          ]);
          setTicketTipos(opTipos);
          setTicketTipo(opTipos[0]?.key || "");
          setTicketAreas(opAreas);
          // Intentar mapear área desde payload de IA si viene
          const aiAreaRaw =
            (detail as any)?.ai?.area || (detail as any)?.overrideArea || null;
          if (aiAreaRaw && opAreas.length) {
            const norm = (s: string) =>
              s
                .toLowerCase()
                .normalize("NFD")
                .replace(/\p{Diacritic}/gu, "")
                .trim();
            const aim = norm(String(aiAreaRaw));
            const match = opAreas.find(
              (a) => norm(a.key) === aim || norm(a.value) === aim
            );
            setTicketArea(match?.key || opAreas[0]?.key || "");
          } else {
            setTicketArea(opAreas[0]?.key || "");
          }
        } catch {
          setTicketTipos([]);
          setTicketTipo("");
          setTicketAreas([]);
          setTicketArea("");
        }
        setTicketArchivos(files);
        setTicketNombre((detail as any).overrideNombre || nombre);
        setTicketPreviewMessages((detail as any).selected || []);
        setTicketAutoGenerated(Boolean((detail as any).autoGenerated));
        setTicketDescripcion(
          ((detail as any).selected || [])
            .map((m: any) => `${m.sender}: ${m.text || ""}`)
            .join("\n")
            .slice(0, 2000)
        );
        setShowTicket(true);
        return;
      }

      // intentar creación automática: dedupe y crear ticket desde el servidor
      try {
        // cargar tipos/áreas si no están y determinar tipo/área por defecto
        let tipoDefault = ticketTipos[0]?.key;
        let areaDefault = ticketAreas[0]?.key;
        if (!tipoDefault || !areaDefault) {
          const [opTipos, opAreas] = await Promise.all([
            !tipoDefault ? getOpciones("tipo_ticket") : Promise.resolve([]),
            !areaDefault ? getOpciones("area") : Promise.resolve([]),
          ]);
          if (!tipoDefault && Array.isArray(opTipos) && opTipos.length) {
            setTicketTipos(opTipos);
            tipoDefault = opTipos[0]?.key || "general";
          }
          if (!areaDefault && Array.isArray(opAreas) && opAreas.length) {
            setTicketAreas(opAreas);
            areaDefault = opAreas[0]?.key || "";
          }
        }

        // dedupe: revisar tickets recientes (24h) para este alumno
        let recentTickets: any[] = [];
        try {
          recentTickets = await getStudentTickets(alumnoCode, []);
        } catch {}
        const now = Date.now();
        const recent = (recentTickets || []).some((t) => {
          const created = t?.creacion ? Date.parse(t.creacion) : 0;
          return created && now - created < 24 * 60 * 60 * 1000;
        });
        if (recent) {
          toast({ title: "Ya existe un ticket reciente para este alumno" });
          return;
        }

        // crear ticket automáticamente
        let autoDescripcion = (detail?.selected || [])
          .map((m: any) => `${m.sender}: ${m.text || ""}`)
          .join("\n")
          .slice(0, 2000);
        // Si viene área desde IA, anteponerla en la descripción
        try {
          const aiAreaRaw =
            (detail as any)?.ai?.area || (detail as any)?.overrideArea || null;
          if (aiAreaRaw) {
            const areas = ticketAreas.length
              ? ticketAreas
              : await getOpciones("area");
            const norm = (s: string) =>
              String(s)
                .toLowerCase()
                .normalize("NFD")
                .replace(/\p{Diacritic}/gu, "")
                .trim();
            const aim = norm(String(aiAreaRaw));
            const match = areas.find(
              (a) => norm(a.key) === aim || norm(a.value) === aim
            );
            const areaLabel = match?.value ?? String(aiAreaRaw);
            autoDescripcion = `Área: ${areaLabel}\n\n${autoDescripcion}`.slice(
              0,
              2000
            );
          } else if (areaDefault) {
            const areas = ticketAreas.length
              ? ticketAreas
              : await getOpciones("area");
            const label =
              areas.find((a) => a.key === areaDefault)?.value || areaDefault;
            autoDescripcion = `Área: ${label}\n\n${autoDescripcion}`.slice(
              0,
              2000
            );
          }
        } catch {}
        const created = await createTicket({
          nombre,
          id_alumno: alumnoCode,
          tipo: tipoDefault,
          descripcion: autoDescripcion,
          archivos: files,
        });
        // Mostrar toast simple y abrir modal con payload para ver detalles
        const payload = created?.data ?? created;
        // Intentar asignar estado por defecto usando opciones
        try {
          const estados = await getOpciones("estado_tickets");
          // Preferir PENDIENTE -> EN_PROGRESO -> primera
          const prefer = ["PENDIENTE", "EN_PROGRESO"];
          let chosen = estados.find((e) => prefer.includes(e.key))?.key;
          if (!chosen) chosen = estados[0]?.key || undefined;
          // Usar solo el campo 'codigo' (UUID) para updateTicket
          const codigo = payload?.codigo ? String(payload.codigo) : undefined;
          if (codigo && chosen) {
            await updateTicket(codigo, { estado: chosen });
          }
        } catch (e) {
          console.error("Failed to set default ticket estado:", e);
        }
        setCreatedTicketPayload(payload);
        setShowCreatedModal(true);
        toast({ title: "Ticket creado exitosamente" });
        return;
      } catch (err) {
        // si falla la creación automática, abrir modal para revisión manual
        console.error("Auto-create ticket failed:", err);
        try {
          const opciones = await getOpciones("tipo_ticket");
          setTicketTipos(opciones);
          setTicketTipo(opciones[0]?.key || "");
        } catch {
          setTicketTipos([]);
          setTicketTipo("");
        }
        setTicketArchivos(files);
        setTicketNombre(nombre);
        setTicketDescripcion(
          ((detail as any).selected || [])
            .map((m: any) => `${m.sender}: ${m.text || ""}`)
            .join("\n")
            .slice(0, 2000)
        );
        setTicketPreviewMessages([]);
        setTicketAutoGenerated(false);
        setShowTicket(true);
      }
    };

    window.addEventListener("chat:create-ticket", handler as EventListener);
    return () =>
      window.removeEventListener(
        "chat:create-ticket",
        handler as EventListener
      );
  }, [all]);

  async function submitTicketFromChat() {
    const alumnoCode = alumnoCodeForTicketRef.current;
    if (!alumnoCode) {
      toast({ title: "Alumno no encontrado" });
      return;
    }
    if (!ticketNombre.trim()) {
      toast({ title: "Agrega un nombre al ticket" });
      return;
    }
    if (!ticketTipo) {
      toast({ title: "Selecciona un tipo de ticket" });
      return;
    }
    try {
      // Prefijar área en la descripción si aplica
      let finalDescripcion = ticketDescripcion.trim();
      try {
        if (ticketArea) {
          const areaLabel =
            ticketAreas.find((a) => a.key === ticketArea)?.value || ticketArea;
          const already = /(^|\n)\s*Área\s*:/i.test(finalDescripcion);
          if (!already) {
            finalDescripcion =
              `Área: ${areaLabel}\n\n${finalDescripcion}`.trim();
          }
        }
      } catch {}
      const created = await createTicket({
        nombre: ticketNombre.trim(),
        id_alumno: alumnoCode,
        tipo: ticketTipo,
        descripcion: finalDescripcion,
        archivos: ticketArchivos,
      });
      const payload = created?.data ?? created;
      // Intentar asignar estado por defecto al ticket creado manualmente
      try {
        const estados = await getOpciones("estado_tickets");
        const prefer = ["PENDIENTE", "EN_PROGRESO"];
        let chosen = estados.find((e) => prefer.includes(e.key))?.key;
        if (!chosen) chosen = estados[0]?.key || undefined;
        // Usar solo el campo 'codigo' (UUID) para updateTicket
        const codigo = payload?.codigo ? String(payload.codigo) : undefined;
        if (codigo && chosen) {
          await updateTicket(codigo, { estado: chosen });
        }
      } catch (e) {
        console.error("Failed to set default ticket estado:", e);
      }
      setCreatedTicketPayload(payload);
      setShowCreatedModal(true);
      toast({ title: "Ticket creado exitosamente" });
      setShowTicket(false);
      setTicketPreviewMessages([]);
      setTicketAutoGenerated(false);
      setTicketArchivos([]);
      setTicketNombre("");
      setTicketTipo("");
      setTicketDescripcion("");
      setTicketArea("");
    } catch (e: any) {
      toast({
        title: "No se pudo crear el ticket",
        description: String(e?.message || e || ""),
      });
    }
  }

  function onAddFilesFromPicker(e: React.ChangeEvent<HTMLInputElement>) {
    const list = e.target.files;
    if (!list || list.length === 0) return;
    const max = 10;
    const next = [...ticketArchivos];
    for (const f of Array.from(list)) {
      if (next.length >= max) break;
      next.push(f);
    }
    setTicketArchivos(next);
    e.target.value = "";
  }

  return (
    <ProtectedRoute allowedRoles={["admin"]}>
      <DashboardLayout>
        <div className="flex flex-col flex-1 min-h-0">
          {/* Contenedor full-bleed para aprovechar todo el espacio disponible */}
          <div className="flex flex-1 overflow-hidden -m-6 sm:-m-6">
            {/* Sidebar de alumnos */}
            <div
              className={`${
                isMobile ? (selected ? "hidden" : "block") : "block"
              } w-full lg:w-96 border-r bg-card flex flex-col min-w-0 min-h-0 overflow-y-auto`}
            >
              <div className="p-4 border-b bg-background/80 backdrop-blur supports-[backdrop-filter]:bg-background/60 sticky top-0 z-10">
                <div className="relative flex items-center gap-2">
                  <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground" />
                  <input
                    value={q}
                    onChange={(e) => setQ(e.target.value)}
                    placeholder="Buscar alumnos..."
                    className="w-full pl-10 pr-4 py-2.5 text-sm bg-background border rounded-lg focus:outline-none focus:ring-2 focus:ring-primary/20"
                  />
                  <div className="absolute right-2 top-1/2 -translate-y-1/2">
                    {/* Popover de filtros */}
                    <div className="relative">
                      <details className="relative">
                        <summary className="list-none cursor-pointer p-1 rounded hover:bg-muted/50">
                          <svg
                            className="w-4 h-4 text-muted-foreground"
                            viewBox="0 0 24 24"
                            fill="none"
                          >
                            <path
                              d="M3 5h18M6 12h12M10 19h4"
                              stroke="currentColor"
                              strokeWidth="1.5"
                              strokeLinecap="round"
                              strokeLinejoin="round"
                            />
                          </svg>
                        </summary>
                        <div className="absolute right-0 mt-2 w-56 bg-white rounded border shadow-md p-3 z-20">
                          <div className="mb-2 text-sm font-semibold">
                            Filtrar conversaciones
                          </div>
                          <div className="mb-2">
                            <div className="text-xs mb-1">Estatus</div>
                            <div className="flex flex-wrap gap-1">
                              {statusOptions.map((s) => (
                                <button
                                  key={s}
                                  onClick={() =>
                                    setStatusFilter(
                                      statusFilter === s ? null : s
                                    )
                                  }
                                  className={`px-2 py-0.5 rounded text-xs ${
                                    statusFilter === s
                                      ? "bg-sky-600 text-white"
                                      : "bg-gray-100"
                                  }`}
                                >
                                  {s.replace("_", " ")}
                                </button>
                              ))}
                            </div>
                          </div>
                          <div>
                            <div className="text-xs mb-1">Fase</div>
                            <div className="flex flex-wrap gap-1">
                              {phaseOptions.map((f) => (
                                <button
                                  key={f}
                                  onClick={() =>
                                    setPhaseFilter(phaseFilter === f ? null : f)
                                  }
                                  className={`px-2 py-0.5 rounded text-xs ${
                                    phaseFilter === f
                                      ? "bg-sky-600 text-white"
                                      : "bg-gray-100"
                                  }`}
                                >
                                  {f}
                                </button>
                              ))}
                            </div>
                          </div>
                          {(statusFilter || phaseFilter) && (
                            <button
                              className="mt-3 text-xs text-sky-600 underline"
                              onClick={() => {
                                setStatusFilter(null);
                                setPhaseFilter(null);
                              }}
                            >
                              Limpiar filtros
                            </button>
                          )}
                        </div>
                      </details>
                    </div>
                  </div>
                </div>
              </div>

              <div className="flex-1">
                {loading && (
                  <div className="p-6 text-center text-sm text-muted-foreground">
                    Cargando conversaciones...
                  </div>
                )}
                {!loading && filtered.length === 0 && (
                  <div className="p-6 text-center text-sm text-muted-foreground">
                    No se encontraron alumnos
                  </div>
                )}
                {filtered.map((s) => {
                  const hasCode = !!(s.code && s.code.trim());
                  const isSelected = selected?.id === s.id;

                  // Lógica de no leídos
                  const room = (s.code || String(s.id)).toLowerCase();
                  const lastRead = getLastRead(room);
                  const lastActivity = s.lastActivity
                    ? new Date(s.lastActivity).getTime()
                    : 0;
                  // Si la actividad es más reciente que mi última lectura, es unread persistente
                  // (Solo si no está seleccionado actualmente)
                  const isUnreadPersistent =
                    lastActivity > lastRead && !isSelected;
                  // Si hay mensajes nuevos en vivo
                  const isUnreadLive = (unreadByRoom[room] || 0) > 0;

                  const isUnread = isUnreadPersistent || isUnreadLive;

                  return (
                    <button
                      key={s.id}
                      onClick={() => hasCode && setSelected(s)}
                      disabled={!hasCode}
                      className={`w-full text-left px-4 py-3 transition-colors border-b border-border/50 last:border-b-0 ${
                        hasCode
                          ? "hover:bg-muted/50 cursor-pointer active:bg-muted"
                          : "opacity-50 cursor-not-allowed"
                      } ${
                        isSelected
                          ? "bg-muted"
                          : isUnread
                          ? "bg-blue-50/40 dark:bg-blue-900/10"
                          : "bg-transparent"
                      }`}
                      title={
                        hasCode ? "Abrir chat" : "Este alumno no tiene código"
                      }
                    >
                      <div className="flex items-center gap-3">
                        <div className="relative">
                          <Avatar className="h-12 w-12 flex-shrink-0">
                            <AvatarFallback
                              className={`${getAvatarColor(
                                s.name
                              )} text-white font-medium`}
                            >
                              {getInitials(s.name)}
                            </AvatarFallback>
                          </Avatar>
                          {isUnread && (
                            <span className="absolute top-0 right-0 h-3 w-3 rounded-full bg-blue-600 border-2 border-background" />
                          )}
                        </div>

                        <div className="flex-1 min-w-0">
                          <div className="flex items-baseline justify-between gap-2 mb-0.5">
                            <h3
                              className={`text-sm truncate text-foreground ${
                                isUnread ? "font-bold" : "font-semibold"
                              }`}
                            >
                              {s.name}
                            </h3>
                            {hasCode && (
                              <span className="text-xs text-muted-foreground flex-shrink-0">
                                {s.stage || ""}
                              </span>
                            )}
                          </div>
                          <p
                            className={`text-xs truncate ${
                              hasCode
                                ? isUnread
                                  ? "text-foreground font-medium"
                                  : "text-muted-foreground"
                                : "text-amber-600 font-medium"
                            }`}
                          >
                            {hasCode
                              ? `Código: ${s.code}`
                              : "Sin código asignado"}
                          </p>
                        </div>
                      </div>
                    </button>
                  );
                })}
              </div>
            </div>

            {/* Panel de conversación */}
            <div
              className={`flex-1 flex flex-col bg-background min-h-0 ${
                isMobile ? (selected ? "block" : "hidden") : "block"
              }`}
            >
              {selected ? (
                !selected.code || !selected.code.trim() ? (
                  <div className="flex items-center justify-center h-full p-6">
                    <div className="rounded-xl border bg-card p-6 text-sm text-amber-700 shadow-sm max-w-md">
                      Este alumno no tiene un código asignado. No se puede
                      iniciar el chat.
                    </div>
                  </div>
                ) : (
                  <ChatRealtime
                    room={(selected.code || String(selected.id)).toLowerCase()}
                    role="admin"
                    title={selected.name}
                    subtitle={`${selected.code ?? ""}`}
                    variant="fullscreen"
                    className="h-full"
                    transport={transport}
                    showRoleSwitch={debug}
                    onBack={isMobile ? () => setSelected(null) : undefined}
                  />
                )
              ) : (
                <div className="flex items-center justify-center h-full p-12">
                  <div className="max-w-sm mx-auto space-y-2 text-center">
                    <h3 className="font-medium text-foreground">
                      Selecciona una conversación
                    </h3>
                    <p className="text-sm text-muted-foreground">
                      Elige un alumno de la lista para iniciar el chat
                    </p>
                  </div>
                </div>
              )}
            </div>
          </div>
        </div>
      </DashboardLayout>
      {/* Modal Crear Ticket desde chat */}
      <Dialog open={showTicket} onOpenChange={setShowTicket}>
        <DialogContent className="sm:max-w-2xl bg-white">
          <DialogHeader>
            <DialogTitle>Crear ticket desde chat</DialogTitle>
          </DialogHeader>
          <div className="space-y-4">
            <div className="space-y-2">
              <Label>Nombre</Label>
              <textarea
                value={ticketNombre}
                onChange={(e) => setTicketNombre(e.target.value)}
                placeholder="Asunto del ticket"
                rows={3}
                className="w-full rounded border px-3 py-2 text-sm bg-white resize-none focus:outline-none focus:ring-2 focus:ring-primary/30"
              />
            </div>
            {/* Preview sugerido y resumen de mensajes */}
            {(ticketPreviewMessages?.length || ticketAutoGenerated) && (
              <div className="space-y-2 border rounded p-3 bg-white">
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-2">
                    <span className="text-xs text-muted-foreground">
                      Sugerencia
                    </span>
                    <span className="px-2 py-0.5 rounded bg-sky-600 text-white text-xs font-medium">
                      {ticketAutoGenerated ? "Generada por IA" : "Seleccionada"}
                    </span>
                  </div>
                  <div className="flex items-center gap-2">
                    <button
                      className="text-xs underline"
                      onClick={() => {
                        const last = String(
                          ticketPreviewMessages?.slice(-1)[0]?.text || ""
                        );
                        const full = (ticketPreviewMessages || [])
                          .map((m: any) => `${m.sender}: ${m.text || ""}`)
                          .join("\n");
                        setTicketNombre((prev) => prev || last.slice(0, 120));
                        setTicketDescripcion(
                          (prev) => prev || full.slice(0, 2000)
                        );
                      }}
                      type="button"
                    >
                      Usar sugerencia
                    </button>
                    <button
                      className="text-xs text-muted-foreground"
                      onClick={() => {
                        setTicketPreviewMessages([]);
                        setTicketAutoGenerated(false);
                      }}
                      type="button"
                    >
                      Ocultar
                    </button>
                  </div>
                </div>
                <div className="mt-2 max-h-40 overflow-y-auto text-sm space-y-2">
                  {ticketPreviewMessages.slice(-5).map((m, idx) => (
                    <div key={idx} className="p-2 rounded bg-white/80">
                      <div className="text-xs text-muted-foreground flex items-center justify-between">
                        <span className="font-semibold text-xs">
                          {(m.sender || "").charAt(0).toUpperCase() +
                            (m.sender || "").slice(1)}
                        </span>
                        <span className="text-[11px]">
                          {new Date(m.at).toLocaleString("es-ES", {
                            timeZone: "UTC",
                            weekday: "short",
                            day: "2-digit",
                            month: "2-digit",
                            hour: "2-digit",
                            minute: "2-digit",
                            hour12: false,
                          })}
                        </span>
                      </div>
                      <div className="text-sm text-gray-900 whitespace-pre-wrap break-words">
                        {String(m.text || "").slice(0, 240)}
                      </div>
                      {m.attachments && m.attachments.length > 0 && (
                        <div className="mt-1 text-xs text-muted-foreground">
                          Adjuntos: {m.attachments.length}
                        </div>
                      )}
                    </div>
                  ))}
                </div>
              </div>
            )}
            {/* Área */}
            <div className="space-y-2">
              <div className="flex items-center justify-between">
                <Label>Área</Label>
              </div>
              <div>
                <Select value={ticketArea} onValueChange={setTicketArea}>
                  <SelectTrigger className="w-full">
                    <SelectValue>
                      {ticketAreas.find((t) => t.key === ticketArea)?.value ||
                        ticketArea ||
                        "Seleccione un área"}
                    </SelectValue>
                  </SelectTrigger>
                  <SelectContent>
                    {ticketAreas.map((op) => (
                      <SelectItem key={op.id} value={op.key}>
                        {op.value}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>
            </div>
            <div className="space-y-2">
              <div className="flex items-center justify-between">
                <Label>Tipo</Label>
                <button
                  type="button"
                  className="text-xs text-muted-foreground underline"
                  onClick={() => {
                    // permitir alternar a edición libre
                    if (ticketTipos.length === 0) return;
                    // si ticketTipo está vacío, preseleccionar el primero
                    if (!ticketTipo) setTicketTipo(ticketTipos[0]?.key || "");
                  }}
                >
                  Editar
                </button>
              </div>

              <div className="grid grid-cols-1 gap-2 sm:grid-cols-2">
                <div>
                  <Select value={ticketTipo} onValueChange={setTicketTipo}>
                    <SelectTrigger className="w-full">
                      <SelectValue>
                        {ticketTipos.find((t) => t.key === ticketTipo)?.value ||
                          ticketTipo ||
                          "Seleccione un tipo"}
                      </SelectValue>
                    </SelectTrigger>
                    <SelectContent>
                      {ticketTipos.map((op) => (
                        <SelectItem key={op.id} value={op.key}>
                          {op.value}
                        </SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                </div>
                <div>
                  <Input
                    value={ticketTipo}
                    onChange={(e) => setTicketTipo(e.target.value)}
                    placeholder="Editar clave de tipo (opcional)"
                  />
                </div>
              </div>
            </div>
            <div className="space-y-2">
              <Label>Descripción</Label>
              <textarea
                value={ticketDescripcion}
                onChange={(e) => setTicketDescripcion(e.target.value)}
                placeholder="Descripción del ticket (puedes editar la sugerencia)"
                rows={4}
                className="w-full rounded border px-3 py-2 text-sm bg-white resize-none focus:outline-none focus:ring-2 focus:ring-primary/30"
              />
            </div>
            <div className="space-y-2">
              <Label>Archivos ({ticketArchivos.length}/10)</Label>
              {ticketArchivos.length === 0 ? (
                <p className="text-xs text-muted-foreground">
                  No hay archivos seleccionados
                </p>
              ) : (
                <ul className="max-h-40 overflow-y-auto text-sm list-disc pl-5 space-y-1">
                  {ticketArchivos.map((f, idx) => (
                    <li
                      key={`${f.name}-${idx}`}
                      className="flex items-center justify-between gap-2"
                    >
                      <span
                        className="truncate"
                        title={`${f.name} • ${(f.size / 1024).toFixed(1)} KB`}
                      >
                        {f.name}
                      </span>
                      <button
                        className="text-xs text-red-600 hover:underline"
                        onClick={() =>
                          setTicketArchivos((prev) =>
                            prev.filter((_, i) => i !== idx)
                          )
                        }
                        type="button"
                      >
                        Quitar
                      </button>
                    </li>
                  ))}
                </ul>
              )}
              <div className="flex gap-2">
                <Button
                  variant="secondary"
                  type="button"
                  onClick={() => filePickerRef.current?.click()}
                >
                  Añadir archivos
                </Button>
                <input
                  ref={filePickerRef}
                  type="file"
                  multiple
                  className="hidden"
                  onChange={onAddFilesFromPicker}
                />
              </div>
            </div>
          </div>
          <DialogFooter>
            <Button
              variant="outline"
              onClick={() => setShowTicket(false)}
              type="button"
            >
              Cancelar
            </Button>
            <Button onClick={submitTicketFromChat} type="button">
              Crear ticket
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
      {/* Modal: Detalles del ticket creado */}
      <Dialog open={showCreatedModal} onOpenChange={setShowCreatedModal}>
        <DialogContent className="sm:max-w-lg bg-white">
          <DialogHeader>
            <DialogTitle className="flex items-center gap-2">
              <CheckCircle className="w-5 h-5 text-emerald-500" />
              <span>Ticket creado exitosamente</span>
            </DialogTitle>
          </DialogHeader>
          <div className="mt-2">
            {createdSummary ? (
              <div className="text-sm text-muted-foreground">
                Se ha creado un ticket del tipo{" "}
                <strong>{createdSummary.tipo}</strong> para el usuario{" "}
                <strong>{createdSummary.alumno}</strong> el día{" "}
                <strong>{createdSummary.fecha}</strong>.
                {createdTicketPayload &&
                  (createdTicketPayload.codigo ||
                    createdTicketPayload.ticketId) && (
                    <div className="mt-2 text-sm">
                      <strong>Código:</strong>{" "}
                      <span className="font-mono text-xs">
                        {createdTicketPayload.codigo ??
                          createdTicketPayload.ticketId}
                      </span>
                    </div>
                  )}
              </div>
            ) : (
              <div className="text-sm text-muted-foreground">
                El ticket se creó correctamente.
              </div>
            )}
          </div>
          <DialogFooter>
            <Button onClick={() => setShowCreatedModal(false)}>Cerrar</Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </ProtectedRoute>
  );
}
